/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardCarousel: typeof import('./components/CardCarousel.vue')['default']
    Category: typeof import('./components/Category.vue')['default']
    CategoryFilter: typeof import('./components/CategoryFilter.vue')['default']
    Discount: typeof import('./components/Discount.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Location: typeof import('./components/Location.vue')['default']
    PillFilter: typeof import('./components/PillFilter.vue')['default']
    PillNavigation: typeof import('./components/PillNavigation.vue')['default']
    PriceCounter: typeof import('./components/PriceCounter.vue')['default']
    RoundCardCarousel: typeof import('./components/RoundCardCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
